# Generated by Django 2.1.2 on 2019-05-31 02:31

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20190531_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_icon_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='user_icon/poddict_icon.jpg', upload_to='user_icon'),
        ),
    ]
