# Generated by Django 2.1.7 on 2019-02-25 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdblog_title', models.CharField(max_length=20)),
                ('pdblog_text', models.CharField(max_length=700)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdwriter_name', models.CharField(max_length=15)),
                ('registered_date', models.DateTimeField(verbose_name='date registered')),
                ('email_address', models.EmailField(max_length=254)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdblog.Article')),
            ],
            options={
                'verbose_name': 'Writer',
                'verbose_name_plural': 'Writers',
            },
        ),
    ]
