# Generated by Django 2.1.2 on 2019-05-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user_icon',
            field=models.ImageField(blank=True, height_field=100, upload_to='user_icon/', width_field=100),
        ),
    ]
