# Generated by Django 2.1.2 on 2019-05-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdblog', '0002_article_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='user_icon',
            field=models.ImageField(blank=True, default='/storage/user_icon/poddict_icon.png', height_field=100, upload_to='user_icon/', width_field=100),
        ),
    ]
