# Generated by Django 2.1.2 on 2019-05-27 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdblog', '0003_auto_20190527_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user_icon',
        ),
    ]
