# Generated by Django 2.1.7 on 2019-04-16 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdblog', '0003_auto_20190415_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllArticles',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('pdblog.article',),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
