# Generated by Django 2.1.8 on 2019-06-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdblog', '0004_remove_article_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
