# Generated by Django 2.1.8 on 2019-06-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdblog', '0006_auto_20190610_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(max_length='512'),
        ),
    ]
