# Generated by Django 2.2 on 2019-05-24 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdblog', '0007_auto_20190505_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=300)),
                ('is_published', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='published date')),
                ('target_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdblog.Article')),
            ],
            options={
                'verbose_name': 'Commnet',
                'verbose_name_plural': 'Comments',
                'ordering': ['-pub_date'],
            },
        ),
    ]
