# Generated by Django 2.1.8 on 2019-06-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdblog', '0007_auto_20190610_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(choices=[('TC', 'Tech'), ('OD', 'Poddcast'), ('NT', 'Notes')], default='TC', max_length=2),
        ),
    ]
