# Generated by Django 2.2 on 2019-05-24 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdblog', '0008_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllComments',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pdblog.comment',),
        ),
    ]
